const NOTIFICATION_TYPES = {
  // ─────────────────────────────────────
  // AUTHENTICATION
  // ─────────────────────────────────────

  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT: "LOGOUT",

  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",

  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",


  // ─────────────────────────────────────
  // PROFILE / VERIFICATION
  // ─────────────────────────────────────

  PROFILE_UPDATED: "PROFILE_UPDATED",

  VERIFICATION_SUBMITTED: "VERIFICATION_SUBMITTED",

  VERIFICATION_COMPLETE: "VERIFICATION_COMPLETE",

  VERIFICATION_REJECTED: "VERIFICATION_REJECTED",

  DOCUMENT_VERIFICATION_PENDING:
    "DOCUMENT_VERIFICATION_PENDING",

  DOCUMENT_VERIFICATION_COMPLETE:
    "DOCUMENT_VERIFICATION_COMPLETE",

  DOCUMENT_VERIFICATION_REJECTED:
    "DOCUMENT_VERIFICATION_REJECTED",


  // ─────────────────────────────────────
  // VEHICLE
  // ─────────────────────────────────────

  VEHICLE_ADDED: "VEHICLE_ADDED",

  VEHICLE_VERIFICATION_PENDING:
    "VEHICLE_VERIFICATION_PENDING",

  VEHICLE_VERIFIED: "VEHICLE_VERIFIED",

  VEHICLE_VERIFICATION_REJECTED:
    "VEHICLE_VERIFICATION_REJECTED",

  VEHICLE_REMOVED: "VEHICLE_REMOVED",


  // ─────────────────────────────────────
  // RIDES
  // ─────────────────────────────────────

  RIDE_PUBLISHED: "RIDE_PUBLISHED",

  RIDE_UPDATED: "RIDE_UPDATED",

  RIDE_CANCELLED: "RIDE_CANCELLED",

  RIDE_COMPLETED: "RIDE_COMPLETED",

  RIDE_STARTING_SOON: "RIDE_STARTING_SOON",

  RIDE_DEPARTURE_CHANGED:
    "RIDE_DEPARTURE_CHANGED",

  RIDE_FULL: "RIDE_FULL",


  // ─────────────────────────────────────
  // BOOKINGS
  // ─────────────────────────────────────

  BOOKING_CREATED: "BOOKING_CREATED",

  RIDE_BOOKING_REQUESTED:
    "RIDE_BOOKING_REQUESTED",

  BOOKING_ACCEPTED: "BOOKING_ACCEPTED",

  BOOKING_REJECTED: "BOOKING_REJECTED",

  BOOKING_CANCELLED: "BOOKING_CANCELLED",

  BOOKING_COMPLETED: "BOOKING_COMPLETED",

  BOOKING_REFUNDED: "BOOKING_REFUNDED",


  // ─────────────────────────────────────
  // PAYMENTS
  // ─────────────────────────────────────

  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",

  PAYMENT_FAILED: "PAYMENT_FAILED",

  PAYMENT_PENDING: "PAYMENT_PENDING",

  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",

  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",

  PAYOUT_PENDING: "PAYOUT_PENDING",

  PAYOUT_PROCESSED: "PAYOUT_PROCESSED",

  PAYOUT_FAILED: "PAYOUT_FAILED",


  // ─────────────────────────────────────
  // SYSTEM
  // ─────────────────────────────────────

  SYSTEM: "SYSTEM",

  SYSTEM_ALERT: "SYSTEM_ALERT",

  MAINTENANCE: "MAINTENANCE",

  PROMOTION: "PROMOTION",

  BROADCAST: "BROADCAST",
};

module.exports = NOTIFICATION_TYPES;